BinarApp/BinarApp.Web/Controllers/EquipmentsController.cs
using BinarApp.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BinarApp.Web.Controllers
{
    public class EquipmentsController : Controller
    {
        // GET: Equipments
        public ActionResult Index(int id, EquipmentItemEnum timeFlat)
        {
            var data = new EquipmentFileUploadViewModel()
            {
                EquipmentId = id,
                IsDay = true
            };

            return View();
        }

        public ActionResult Post(EquipmentFileUploadViewModel model)
        {


            return Redirect("/Home/Equipments");
        }

    }
}

BinarApp/BinarApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    <script src="~/Scripts/jszip.min.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Styles.Render("~/Content/DevExtremeBundle")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/Scripts/DevExtremeBundle")

    @*@Scripts.Render("~/Content/leaflet")*@

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.4/dist/leaflet.css"
          integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
          crossorigin="" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/0.2.3/leaflet.draw.css" />

    <script src="https://unpkg.com/leaflet@1.3.4/dist/leaflet.js"
            integrity="sha512-nMMmRyTVoLYqjP9hrbed9S+FzjZHW5gY1TWCHA5ckwXZBadntCNs8kEqAWdrb9O7rxbCaA4lKTIWjDXZxflOcA=="
            crossorigin=""></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/0.4.2/leaflet.draw.js"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Rapid", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Парковки", "Equipments", "Home")</li>
                    <li>@Html.ActionLink("Карта", "MatchEquipmentToMap", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    @*<div class="container body-content">

            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
            </footer>
        </div>*@
    @RenderBody()

    @Scripts.Render("~/bundles/bootstrap")
    @*@Scripts.Render("~/bundles/leaflet")*@

    @RenderSection("scripts", required: false)
</body>
</html>